network:
  proxy_url: "http://127.0.0.1:7890"
  header:
    Referer: "https://www.pixiv.net/"
    User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
  cookies:


setting:
  path: "D:/qb"


